//go:build go1.22

// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
)

// CreateToolCall Governance identity, destination, credential, and retry overrides are prohibited. Idempotent replays must use the same exact tool version and canonical arguments.
type CreateToolCall struct {
	Arguments interface{} `json:"arguments"`
	ToolId    string      `json:"tool_id"`

	// Version Exact immutable SemVer. When omitted, the tenant's configured default is resolved once and persisted.
	Version *string `json:"version,omitempty"`
}

// Problem defines model for Problem.
type Problem struct {
	Code                 interface{}            `json:"code"`
	CorrelationId        string                 `json:"correlation_id"`
	Detail               *string                `json:"detail,omitempty"`
	Instance             *string                `json:"instance,omitempty"`
	Status               int                    `json:"status"`
	Title                string                 `json:"title"`
	Type                 string                 `json:"type"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// PublishToolVersion defines model for PublishToolVersion.
type PublishToolVersion struct {
	Approval                  interface{}            `json:"approval"`
	ConnectorOperation        string                 `json:"connector_operation"`
	CredentialBindingSelector map[string]interface{} `json:"credential_binding_selector"`
	Description               string                 `json:"description"`
	InputSchema               map[string]interface{} `json:"input_schema"`
	Limits                    map[string]interface{} `json:"limits"`
	Metering                  map[string]interface{} `json:"metering"`
	OpenWorldResult           bool                   `json:"open_world_result"`
	OutputSchema              map[string]interface{} `json:"output_schema"`
	ResourceProjection        map[string]interface{} `json:"resource_projection"`
	RetryClass                interface{}            `json:"retry_class"`
	Risk                      interface{}            `json:"risk"`
	SideEffect                bool                   `json:"side_effect"`
	ToolId                    string                 `json:"tool_id"`
	Version                   string                 `json:"version"`
}

// TenantToolExposure defines model for TenantToolExposure.
type TenantToolExposure struct {
	Enabled  bool   `json:"enabled"`
	TenantId string `json:"tenant_id"`
	ToolId   string `json:"tool_id"`
	Version  string `json:"version"`
}

// Tool defines model for Tool.
type Tool struct {
	Approval        interface{}            `json:"approval"`
	Description     string                 `json:"description"`
	InputSchema     map[string]interface{} `json:"input_schema"`
	OpenWorldResult bool                   `json:"open_world_result"`
	OutputSchema    map[string]interface{} `json:"output_schema"`
	RetryClass      interface{}            `json:"retry_class"`
	Risk            interface{}            `json:"risk"`
	SideEffect      bool                   `json:"side_effect"`
	ToolId          string                 `json:"tool_id"`
	Version         string                 `json:"version"`
}

// ToolCall defines model for ToolCall.
type ToolCall struct {
	ApprovalReference *string   `json:"approval_reference,omitempty"`
	CreatedAt         time.Time `json:"created_at"`
	ErrorCode         *string   `json:"error_code,omitempty"`

	// Result Finalized safe result; raw connector/provider output is never returned.
	Result     interface{} `json:"result,omitempty"`
	State      interface{} `json:"state"`
	ToolCallId ToolCallId  `json:"tool_call_id"`
	ToolId     string      `json:"tool_id"`
	UpdatedAt  time.Time   `json:"updated_at"`
	Version    string      `json:"version"`
}

// ToolCallId defines model for ToolCallId.
type ToolCallId = string

// ToolPage defines model for ToolPage.
type ToolPage struct {
	Items      []Tool  `json:"items"`
	NextCursor *string `json:"next_cursor,omitempty"`
}

// Cursor defines model for Cursor.
type Cursor = string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = ToolCallId

// Limit defines model for Limit.
type Limit = int

// ToolId defines model for ToolId.
type ToolId = string

// CreateToolCallParams defines parameters for CreateToolCall.
type CreateToolCallParams struct {
	// IdempotencyKey Stable logical tool_call_id; a transport request ID is insufficient.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ListToolsParams defines parameters for ListTools.
type ListToolsParams struct {
	// Cursor Opaque, integrity-protected, context-bound, expiring continuation cursor.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetToolParams defines parameters for GetTool.
type GetToolParams struct {
	// Version Exact immutable SemVer; describe never selects a floating version.
	Version string `form:"version" json:"version"`
}

// SetTenantToolExposureJSONRequestBody defines body for SetTenantToolExposure for application/json ContentType.
type SetTenantToolExposureJSONRequestBody = TenantToolExposure

// PublishToolVersionJSONRequestBody defines body for PublishToolVersion for application/json ContentType.
type PublishToolVersionJSONRequestBody = PublishToolVersion

// CreateToolCallJSONRequestBody defines body for CreateToolCall for application/json ContentType.
type CreateToolCallJSONRequestBody = CreateToolCall

// Getter for additional properties for Problem. Returns the specified
// element and whether it was found
func (a Problem) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Problem
func (a *Problem) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Problem to handle AdditionalProperties
func (a *Problem) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &a.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
		delete(object, "code")
	}

	if raw, found := object["correlation_id"]; found {
		err = json.Unmarshal(raw, &a.CorrelationId)
		if err != nil {
			return fmt.Errorf("error reading 'correlation_id': %w", err)
		}
		delete(object, "correlation_id")
	}

	if raw, found := object["detail"]; found {
		err = json.Unmarshal(raw, &a.Detail)
		if err != nil {
			return fmt.Errorf("error reading 'detail': %w", err)
		}
		delete(object, "detail")
	}

	if raw, found := object["instance"]; found {
		err = json.Unmarshal(raw, &a.Instance)
		if err != nil {
			return fmt.Errorf("error reading 'instance': %w", err)
		}
		delete(object, "instance")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["title"]; found {
		err = json.Unmarshal(raw, &a.Title)
		if err != nil {
			return fmt.Errorf("error reading 'title': %w", err)
		}
		delete(object, "title")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Problem to handle AdditionalProperties
func (a Problem) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["code"], err = json.Marshal(a.Code)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'code': %w", err)
	}

	object["correlation_id"], err = json.Marshal(a.CorrelationId)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'correlation_id': %w", err)
	}

	if a.Detail != nil {
		object["detail"], err = json.Marshal(a.Detail)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'detail': %w", err)
		}
	}

	if a.Instance != nil {
		object["instance"], err = json.Marshal(a.Instance)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'instance': %w", err)
		}
	}

	object["status"], err = json.Marshal(a.Status)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'status': %w", err)
	}

	object["title"], err = json.Marshal(a.Title)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'title': %w", err)
	}

	object["type"], err = json.Marshal(a.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Live Report process liveness without checking dependencies.
	// (GET /livez)
	Live(w http.ResponseWriter, r *http.Request)
	// Ready Report readiness for the declared dependency posture.
	// (GET /readyz)
	Ready(w http.ResponseWriter, r *http.Request)
	// SetTenantToolExposure Set tenant exposure through separate admin authority.
	// (PUT /v1/admin/tenant-tool-exposures)
	SetTenantToolExposure(w http.ResponseWriter, r *http.Request)
	// PublishToolVersion Publish an immutable tool version through separate admin authority.
	// (POST /v1/admin/tool-versions)
	PublishToolVersion(w http.ResponseWriter, r *http.Request)
	// CreateToolCall Acquire and process one governed logical tool call.
	// (POST /v1/tool-calls)
	CreateToolCall(w http.ResponseWriter, r *http.Request, params CreateToolCallParams)
	// GetToolCall Read a tool call scoped to authenticated tenant and run.
	// (GET /v1/tool-calls/{tool_call_id})
	GetToolCall(w http.ResponseWriter, r *http.Request, toolCallId ToolCallId)
	// ListTools List exposed and authorized tool versions.
	// (GET /v1/tools)
	ListTools(w http.ResponseWriter, r *http.Request, params ListToolsParams)
	// GetTool Describe an exposed tool version.
	// (GET /v1/tools/{tool_id})
	GetTool(w http.ResponseWriter, r *http.Request, toolId ToolId, params GetToolParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Live operation middleware
func (siw *ServerInterfaceWrapper) Live(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Live(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Ready operation middleware
func (siw *ServerInterfaceWrapper) Ready(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Ready(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetTenantToolExposure operation middleware
func (siw *ServerInterfaceWrapper) SetTenantToolExposure(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetTenantToolExposure(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PublishToolVersion operation middleware
func (siw *ServerInterfaceWrapper) PublishToolVersion(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PublishToolVersion(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateToolCall operation middleware
func (siw *ServerInterfaceWrapper) CreateToolCall(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateToolCallParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateToolCall(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetToolCall operation middleware
func (siw *ServerInterfaceWrapper) GetToolCall(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "tool_call_id" -------------
	var toolCallId ToolCallId

	err = runtime.BindStyledParameterWithOptions("simple", "tool_call_id", r.PathValue("tool_call_id"), &toolCallId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tool_call_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetToolCall(w, r, toolCallId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTools operation middleware
func (siw *ServerInterfaceWrapper) ListTools(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListToolsParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTools(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTool operation middleware
func (siw *ServerInterfaceWrapper) GetTool(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "tool_id" -------------
	var toolId ToolId

	err = runtime.BindStyledParameterWithOptions("simple", "tool_id", r.PathValue("tool_id"), &toolId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tool_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetToolParams

	// ------------- Required query parameter "version" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "version", r.URL.Query(), &params.Version, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "version"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "version", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTool(w, r, toolId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/tools", wrapper.ListTools)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/tools/{tool_id}", wrapper.GetTool)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/tool-calls", wrapper.CreateToolCall)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/tool-calls/{tool_call_id}", wrapper.GetToolCall)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/admin/tool-versions", wrapper.PublishToolVersion)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/v1/admin/tenant-tool-exposures", wrapper.SetTenantToolExposure)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/livez", wrapper.Live)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/readyz", wrapper.Ready)

	return m
}

type ProblemApplicationProblemPlusJSONResponse Problem

type LiveRequestObject struct {
}

type LiveResponseObject interface {
	VisitLiveResponse(w http.ResponseWriter) error
}

type Live200Response struct {
}

func (response Live200Response) VisitLiveResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type Live400ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response Live400ApplicationProblemPlusJSONResponse) VisitLiveResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ReadyRequestObject struct {
}

type ReadyResponseObject interface {
	VisitReadyResponse(w http.ResponseWriter) error
}

type Ready200Response struct {
}

func (response Ready200Response) VisitReadyResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type Ready400ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response Ready400ApplicationProblemPlusJSONResponse) VisitReadyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Ready503ApplicationProblemPlusJSONResponse Problem

func (response Ready503ApplicationProblemPlusJSONResponse) VisitReadyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type SetTenantToolExposureRequestObject struct {
	Body *SetTenantToolExposureJSONRequestBody
}

type SetTenantToolExposureResponseObject interface {
	VisitSetTenantToolExposureResponse(w http.ResponseWriter) error
}

type SetTenantToolExposure200Response struct {
}

func (response SetTenantToolExposure200Response) VisitSetTenantToolExposureResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type SetTenantToolExposure400ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response SetTenantToolExposure400ApplicationProblemPlusJSONResponse) VisitSetTenantToolExposureResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type SetTenantToolExposuredefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response SetTenantToolExposuredefaultApplicationProblemPlusJSONResponse) VisitSetTenantToolExposureResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type PublishToolVersionRequestObject struct {
	Body *PublishToolVersionJSONRequestBody
}

type PublishToolVersionResponseObject interface {
	VisitPublishToolVersionResponse(w http.ResponseWriter) error
}

type PublishToolVersion201JSONResponse Tool

func (response PublishToolVersion201JSONResponse) VisitPublishToolVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type PublishToolVersion400ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response PublishToolVersion400ApplicationProblemPlusJSONResponse) VisitPublishToolVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PublishToolVersiondefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response PublishToolVersiondefaultApplicationProblemPlusJSONResponse) VisitPublishToolVersionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CreateToolCallRequestObject struct {
	Params CreateToolCallParams
	Body   *CreateToolCallJSONRequestBody
}

type CreateToolCallResponseObject interface {
	VisitCreateToolCallResponse(w http.ResponseWriter) error
}

type CreateToolCall200JSONResponse ToolCall

func (response CreateToolCall200JSONResponse) VisitCreateToolCallResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateToolCall202JSONResponse ToolCall

func (response CreateToolCall202JSONResponse) VisitCreateToolCallResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type CreateToolCall400ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response CreateToolCall400ApplicationProblemPlusJSONResponse) VisitCreateToolCallResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateToolCall403ApplicationProblemPlusJSONResponse Problem

func (response CreateToolCall403ApplicationProblemPlusJSONResponse) VisitCreateToolCallResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateToolCall404ApplicationProblemPlusJSONResponse Problem

func (response CreateToolCall404ApplicationProblemPlusJSONResponse) VisitCreateToolCallResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateToolCall409ApplicationProblemPlusJSONResponse Problem

func (response CreateToolCall409ApplicationProblemPlusJSONResponse) VisitCreateToolCallResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateToolCalldefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response CreateToolCalldefaultApplicationProblemPlusJSONResponse) VisitCreateToolCallResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetToolCallRequestObject struct {
	ToolCallId ToolCallId `json:"tool_call_id"`
}

type GetToolCallResponseObject interface {
	VisitGetToolCallResponse(w http.ResponseWriter) error
}

type GetToolCall200JSONResponse ToolCall

func (response GetToolCall200JSONResponse) VisitGetToolCallResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetToolCall400ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response GetToolCall400ApplicationProblemPlusJSONResponse) VisitGetToolCallResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetToolCall404ApplicationProblemPlusJSONResponse Problem

func (response GetToolCall404ApplicationProblemPlusJSONResponse) VisitGetToolCallResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetToolCalldefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetToolCalldefaultApplicationProblemPlusJSONResponse) VisitGetToolCallResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListToolsRequestObject struct {
	Params ListToolsParams
}

type ListToolsResponseObject interface {
	VisitListToolsResponse(w http.ResponseWriter) error
}

type ListTools200JSONResponse ToolPage

func (response ListTools200JSONResponse) VisitListToolsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListTools400ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response ListTools400ApplicationProblemPlusJSONResponse) VisitListToolsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListToolsdefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response ListToolsdefaultApplicationProblemPlusJSONResponse) VisitListToolsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetToolRequestObject struct {
	ToolId ToolId `json:"tool_id"`
	Params GetToolParams
}

type GetToolResponseObject interface {
	VisitGetToolResponse(w http.ResponseWriter) error
}

type GetTool200JSONResponse Tool

func (response GetTool200JSONResponse) VisitGetToolResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetTool400ApplicationProblemPlusJSONResponse struct {
	ProblemApplicationProblemPlusJSONResponse
}

func (response GetTool400ApplicationProblemPlusJSONResponse) VisitGetToolResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetTool404ApplicationProblemPlusJSONResponse Problem

func (response GetTool404ApplicationProblemPlusJSONResponse) VisitGetToolResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetTooldefaultApplicationProblemPlusJSONResponse struct {
	Body       Problem
	StatusCode int
}

func (response GetTooldefaultApplicationProblemPlusJSONResponse) VisitGetToolResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Live Report process liveness without checking dependencies.
	// (GET /livez)
	Live(ctx context.Context, request LiveRequestObject) (LiveResponseObject, error)
	// Ready Report readiness for the declared dependency posture.
	// (GET /readyz)
	Ready(ctx context.Context, request ReadyRequestObject) (ReadyResponseObject, error)
	// SetTenantToolExposure Set tenant exposure through separate admin authority.
	// (PUT /v1/admin/tenant-tool-exposures)
	SetTenantToolExposure(ctx context.Context, request SetTenantToolExposureRequestObject) (SetTenantToolExposureResponseObject, error)
	// PublishToolVersion Publish an immutable tool version through separate admin authority.
	// (POST /v1/admin/tool-versions)
	PublishToolVersion(ctx context.Context, request PublishToolVersionRequestObject) (PublishToolVersionResponseObject, error)
	// CreateToolCall Acquire and process one governed logical tool call.
	// (POST /v1/tool-calls)
	CreateToolCall(ctx context.Context, request CreateToolCallRequestObject) (CreateToolCallResponseObject, error)
	// GetToolCall Read a tool call scoped to authenticated tenant and run.
	// (GET /v1/tool-calls/{tool_call_id})
	GetToolCall(ctx context.Context, request GetToolCallRequestObject) (GetToolCallResponseObject, error)
	// ListTools List exposed and authorized tool versions.
	// (GET /v1/tools)
	ListTools(ctx context.Context, request ListToolsRequestObject) (ListToolsResponseObject, error)
	// GetTool Describe an exposed tool version.
	// (GET /v1/tools/{tool_id})
	GetTool(ctx context.Context, request GetToolRequestObject) (GetToolResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// Live operation middleware
func (sh *strictHandler) Live(w http.ResponseWriter, r *http.Request) {
	var request LiveRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Live(ctx, request.(LiveRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Live")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LiveResponseObject); ok {
		if err := validResponse.VisitLiveResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Ready operation middleware
func (sh *strictHandler) Ready(w http.ResponseWriter, r *http.Request) {
	var request ReadyRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Ready(ctx, request.(ReadyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Ready")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ReadyResponseObject); ok {
		if err := validResponse.VisitReadyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SetTenantToolExposure operation middleware
func (sh *strictHandler) SetTenantToolExposure(w http.ResponseWriter, r *http.Request) {
	var request SetTenantToolExposureRequestObject

	var body SetTenantToolExposureJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SetTenantToolExposure(ctx, request.(SetTenantToolExposureRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SetTenantToolExposure")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SetTenantToolExposureResponseObject); ok {
		if err := validResponse.VisitSetTenantToolExposureResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PublishToolVersion operation middleware
func (sh *strictHandler) PublishToolVersion(w http.ResponseWriter, r *http.Request) {
	var request PublishToolVersionRequestObject

	var body PublishToolVersionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PublishToolVersion(ctx, request.(PublishToolVersionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PublishToolVersion")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PublishToolVersionResponseObject); ok {
		if err := validResponse.VisitPublishToolVersionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateToolCall operation middleware
func (sh *strictHandler) CreateToolCall(w http.ResponseWriter, r *http.Request, params CreateToolCallParams) {
	var request CreateToolCallRequestObject

	request.Params = params

	var body CreateToolCallJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateToolCall(ctx, request.(CreateToolCallRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateToolCall")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateToolCallResponseObject); ok {
		if err := validResponse.VisitCreateToolCallResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetToolCall operation middleware
func (sh *strictHandler) GetToolCall(w http.ResponseWriter, r *http.Request, toolCallId ToolCallId) {
	var request GetToolCallRequestObject

	request.ToolCallId = toolCallId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetToolCall(ctx, request.(GetToolCallRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetToolCall")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetToolCallResponseObject); ok {
		if err := validResponse.VisitGetToolCallResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListTools operation middleware
func (sh *strictHandler) ListTools(w http.ResponseWriter, r *http.Request, params ListToolsParams) {
	var request ListToolsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListTools(ctx, request.(ListToolsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTools")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListToolsResponseObject); ok {
		if err := validResponse.VisitListToolsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTool operation middleware
func (sh *strictHandler) GetTool(w http.ResponseWriter, r *http.Request, toolId ToolId, params GetToolParams) {
	var request GetToolRequestObject

	request.ToolId = toolId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTool(ctx, request.(GetToolRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTool")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetToolResponseObject); ok {
		if err := validResponse.VisitGetToolResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
